version: 3

tasks:
  build:
    desc: Build
    cmds:
      - goreleaser build --snapshot --clean

  build-single:
    desc: Build (single)
    cmds:
      - goreleaser build --snapshot --clean --single-target --output dist/coptonix-rs232c-i2c

  dependencyUpdates:
    desc: Show dependency updates
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct

  lint:
    desc: Lint
    cmds:
      - golangci-lint run

  mingo:
    cmds:
      - mise exec go@1.25.3 -- mise install 'go:github.com/bobg/mingo/cmd/mingo@0.14.0'
      - mise exec 'go:github.com/bobg/mingo/cmd/mingo@0.14.0' -- mingo -tests -v
